spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/umdb'
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 499574447944-etuahe4c0q3b30dqep4eor46v1k8r53j.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile