FROM node:16

RUN npm install -g http-server

WORKDIR /app
# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./
# install project dependencies
RUN npm install
# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

EXPOSE 8081

RUN npm run build

CMD [ "http-server", "dist" ]